transport: smtp
smtp_host: 127.0.0.1
smtp_port: 1025
smtp_encryption: '0'
smtp_username: ''
smtp_password: ''
sendmail_path: /usr/sbin/sendmail
sendmail_mode: bs
spool_directory: ''
_core:
  default_config_hash: 0SeYZshzgoabDrbz-junYqeQOQ9BypPv2gaFcnqKy0M
