display:
  default:
    display_title: Hoofd
    display_options:
      exposed_form:
        options:
          submit_button: Toepassen
          reset_button_label: Reset
          exposed_sorts_label: 'Sorteren op'
      pager:
        options:
          expose:
            items_per_page_label: 'Items per pagina'
            items_per_page_options_all_label: '- Alle -'
          tags:
            previous: '‹ vorige'
            next: 'volgende ›'
            first: '« eerste'
            last: 'laatste »'
      fields:
        sent_date:
          label: Datum
        subject:
          label: Onderwerp
        header_to:
          label: Naar
  page_1:
    display_title: Pagina
