<?php
use Drupal\Component\Utility\SafeMarkup;

/**
 * Implements hook_mail().
 */
function contact_form_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
 
  switch ($key) {
    case 'contact_form_mail':
     $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['from'] = $params['from'];
      $message['name'] = $params['name'];
      $message['subject'] = $params['subject'];
      $message['base_root'] = $params['base_root'];
      $message['message'] = SafeMarkup::checkPlain($params['message']);
      break;
  }
}

/**
 * Implements hook_theme_registry_alter().
 *
 * @param $theme_registry
 */
function contact_form_theme_registry_alter(&$theme_registry) {
  // Override cookie compliance default templates.
  $theme_registry['swiftmailer'] = array (
    'template'    => 'swiftmailer',
    'type'        => 'module',
    'path'        => 'modules/custom/contact_form/templates',
    'variables'   => array (
      'message'         => array()
    )
  );
}

?>