<?php

/**
 * @file
 * Contains jdrupal.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_help().
 */
function jdrupal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.jdrupal':
      return Link::fromTextAndUrl(
        t('Getting Started with jDrupal'),
        Url::fromUri('http://jdrupal.easystreet3.com')
      )->toString();
    default:
  }
}

/**
 * Implements hook_menu().
 */
function jdrupal_menu() {
  $items['admin/config/services/jdrupal'] = array(
    'title' => 'jDrupal',
    'description' => 'The jDrupal configuration page.',
    'route_name' => 'jdrupal.config',
  );
  return $items;
}
